export const mentors = [
  {
    _id: 0,
    name: "Ruby Perrin",
    majors: "MDS - Periodontology and Oral Implantology, BDS",
    location: "Islamabad, Pakistan",
    fees: "$70 - $100",
    rating: 5,
  },

  {
    _id: 1,
    name: "Darren Elder",
    majors: "BDS, MDS - Oral & Maxillofacial Surgery",
    location: "Islamabad, Pakistan",
    fees: "$30 - $50",
    rating: 4,
  },
  {
    _id: 2,
    name: "Deborah Angel",
    majors: "BDS, MDS - Oral &amp; Maxillofacial Surgery",
    location: "Islamabad, Pakistan",
    fees: "$30 - $50",
    rating: 3,
  },
  {
    _id: 3,
    name: "Haniya Siddiqui",
    majors: "Management",
    location: "Islamabad, Pakistan",
    fees: "$30 - $50",
    rating: 4,
  },
  {
    _id: 4,
    name: "Deborah Angel",
    majors: "MBBS, MD - General Medicine, DNB - Cardiology",
    location: "Islamabad, Pakistan",
    fees: "$30 - $50",
    rating: 3,
  },
  {
    _id: 5,
    name: "Ghaliyah Siddiqui",
    majors: "Computer Sciences",
    location: "Islamabad, Pakistan",
    fees: "$30 - $50",
    rating: 4,
  },
  {
    _id: 6,
    name: "Deborah Angel",
    majors: "MBBS, MD - General Medicine, DNB - Cardiology",
    location: "Islamabad, Pakistan",
    fees: "$30 - $50",
    rating: 4,
  },
  {
    _id: 7,
    name: "Deborah Angel",
    majors: "MBBS, MD - General Medicine, DNB - Cardiology",
    location: "Islamabad, Pakistan",
    fees: "$30 - $50",
    rating: 4,
  },
  {
    _id: 8,
    name: "Deborah Angel",
    majors: "MBBS, MD - General Medicine, DNB - Cardiology",
    location: "Islamabad, Pakistan",
    fees: "$30 - $50",
    rating: 4,
  },
];

